[project]
name = "task-creator-via-ollama"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.4.1",
    "httpx>=0.28.1",
]

[build-system]
requires = ["uv-build>=0.11.16,<0.12"]
build-backend = "uv_build"

[project.scripts]
task = "task_creator_via_ollama.main:main"
